config/routes.rb
Rails.application.routes.draw do
    #standard route
    root      'pages#home'
    match     'contact' => 'contacts#new', via: [:get, :post]
    resources :products
    resources :cart_items, only: [:create, :update, :destroy], constraints: {format: 'js'}
    match     'cart' => 'carts#show', via: :get
    resources :carts, only: [:index, :destroy]
    match     'checkout' => 'orders#new', via: :get
    resources :orders, except: [:new]

    #devise
    devise_for :admins, skip: [:registrations, :unlock]
    devise_scope :admin do
        post "/admins/unlock" => "devise/unlocks#create", as: :admin_unlock
        get "/admins/unlock" => "devise/unlocks#show", as: ''
    end

    #console
    get 'console', to: 'console#core'
    #admin manager
    resources :admins, except: [:index, :show]
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_one :shipping, inverse_of: :order, dependent: :destroy
  has_one :billing, inverse_of: :order, dependent: :destroy

  accepts_nested_attributes_for :shipping, reject_if: :all_blank
  accepts_nested_attributes_for :billing, reject_if: :all_blank

  validate :suffice_stock?
  validates :cart,
    presence: true
  validates :phone,
    presence: true,
    length: { maximum: 30 }
  validates :email,
    presence: true,
    length: { maximum: 50 },
    format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
  validates :ip_address,
    presence: true,
    format: { with: Resolv::AddressRegex }
  validates :transaction_id,
    length: { maximum: 10 }

  before_save :clean_up
  after_save :mark_as_purchased

  def purchase_with(payment_nonce)
    @result = Braintree::Transaction.sale(
      amount: cart.total,
      payment_method_nonce: payment_nonce,
      customer: {
        first_name: billing.name,
        phone: phone,
        email: email
      },
      billing: {
        first_name: billing.name,
        street_address: billing.street_address,
        extended_address: billing.extended_address,
        locality: billing.city,
        region: billing.state,
        postal_code: billing.postal_code,
        country_name: billing.country
      },
      shipping: {
        first_name: shipping.name,
        street_address: shipping.street_address,
        extended_address: shipping.extended_address,
        locality: shipping.city,
        region: shipping.state,
        postal_code: shipping.postal_code,
        country_name: shipping.country
      },
      options: {
        submit_for_settlement: true
      }
    )

    puts_result
  end

  private
  def suffice_stock?

  end

  def clean_up
    self.email = email.strip.downcase
  end

  def puts_result
    if @result.success?
      puts "success!: #{@result.transaction.id}"
      self.transaction_id = @result.transaction.id
      return true
    elsif @result.transaction
      puts "Error processing transaction:"
      puts "  code: #{@result.transaction.processor_@result_code}"
      puts "  text: #{@result.transaction.processor_@result_text}"
    else
      @result.errors.each do |error|
        puts error.message
        return false
      end
    end
  end

  def mark_as_purchased
    cart.purchase
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include CurrentCart

    before_action :set_format
    before_action :get_cart
    before_action :set_order, only: [:show, :edit, :update, :destroy]

    def index
        @orders = Order.all
    end

    def show
    end

    def new
        if cart?
            @order = Order.new
            build_nested
            set_client_token
        end
    end

    def edit
    end

    def create
        @order = @cart.build_order(order_params)
        @order.ip_address = request.remote_ip
        if @order.valid? && @order.purchase_with(params[:payment_method_nonce])
            @order.save!
            get_new_cart
            redirect_to products_url, notice: 'Order was successfully created.'
        else
            build_nested
            @order.valid?
            set_client_token
            render :new
        end
    end

    def update
        if @order.update(order_params)
            redirect_to @order, notice: 'Order was successfully updated.'
        else
            render :edit
        end
    end
    def destroy
        if @order.destroy
            redirect_to orders_url, notice: 'Order was successfully destroyed.'
        else
            redirect_to orders_url, alert: 'Something went wrong.'
        end
    end

    private
    def set_format
        request.format = 'html'
    end

    def set_order
        @order = Order.find(params[:id])
    end

    def order_params
        params.require(:order).permit(:phone, :email,
                                    shipping_attributes: [:name, :street_address, :extended_address, :city, :state, :postal_code, :country],
                                    billing_attributes: [:name, :street_address, :extended_address, :city, :state, :postal_code, :country])
    end

    def build_nested
        @order.build_shipping unless @order.shipping
        @order.build_billing unless @order.billing
    end

    def set_client_token
        gon.client_token = Braintree::ClientToken.generate
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_address_form.html.erb
<div class="address_form">
  <div class="form_title">
    <p><%= title %></p>
    <%= render 'billing_toggle' if title == 'Billing info' %>
  </div>
  <%= builder.input :name %>
  <%= builder.input :street_address %>
  <%= builder.input :extended_address %>
  <div class="row">
    <%= builder.input :city, wrapper_html: { class: 'city-state' } %>
    <%= builder.input :state, wrapper_html: { class: 'city-state' } %>
  </div>
  <%= builder.input :postal_code %>
  <%= builder.input :country, prompt: true, input_html: { class: 'browser-default' } %>
</div>

app/views/orders/_billing_toggle.html.erb
<div class="billing_toggle">
  <a id="address_duplicate" class="btn-flat waves-effect tooltipped" data-position="left" data-delay="50" data-tooltip="Copy from shipping">
    <i class="tiny material-icons">content_copy</i>
  </a>
</div>

app/views/orders/_card_info.html.erb
<div class="seperator"></div>
<div class="row">
  <div id="dropin" class="col s12 m10 offset-m1"></div>
</div>

app/views/orders/_contact_form.html.erb
<div class="contact_form">
  <p>Contact info</p>
  <%= f.input :phone, wrapper_html: { class: 'iconed' } do %>
    <i class="material-icons prefix">phone</i>
    <%= f.input_field :phone %>
  <% end %>
  <%= f.input :email, wrapper_html: { class: 'iconed' } do %>
    <i class="material-icons prefix">email</i>
    <%= f.input_field :email %>
  <% end %>
</div>

app/views/orders/_customer_info.html.erb
<div class="clear-text">
  <div class="address_forms">
    <%= f.simple_fields_for(:shipping, defaults: { input_html: { class: 'shipping', autocomplete: 'off' } }) do |shipping_builder| %>
      <%= render 'address_form', title: 'Shipping info', builder: shipping_builder %>
    <% end %>
    <%= f.simple_fields_for(:billing, defaults: { input_html: { class: 'billing', autocomplete: 'off' } }) do |billing_builder| %>
      <%= render 'address_form',title: 'Billing info', builder: billing_builder %>
    <% end %>
  </div>
  <div class="divider"></div>
  <%= render 'contact_form', f: f %>
</div>

app/views/orders/_empty.html.erb
<div class="center-align empty">
    <br>
    <p class="flow-text">Nothing in cart.</p>
</div>

app/views/orders/_form.html.erb
<div class="form-section-wrapper">
  <div class="form-section">
    <%= render @cart %>
  </div>
  <%= simple_form_for(@order, html: { class: 'container' }) do |f| %>
    <div class="form-section">
      <%= render 'customer_info', f: f %>
    </div>
    <div class="form-section">
      <%= render 'card_info' %>
      <div class="form-actions center row">
        <div class="seperator"></div>
        <%= f.button :submit, 'Checkout', class: 'btn-flat btn-border waves-effect waves-light purple-text', data: { disable_with: "Please wait..." } %>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/_progress.html.erb
<div class="progress-wrapper row">
  <div class="col s12 m8 offset-m2">
    <div class="progress">
      <div class="determinate" style="width: 0"></div>
    </div>
    <div>
      <div class="btn-progress">
        <a class="step" progress='0%' stage='1'><i class="material-icons">shopping_cart</i></a>
      </div>
      <div class="btn-progress">
        <a class="step" progress='50%' stage='2'><i class="material-icons">person</i></a>
      </div>
      <div class="btn-progress">
        <a class="step" progress='100%' stage='3'><i class="material-icons">payment</i></a>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', checkout_path %>

app/views/orders/new.html.erb
<%= render 'progress' %>
<% if !@cart.nil? && !@cart.cart_items.blank? %>
    <%= render 'form' %>
<% else %>
    <%= render 'empty' %>
<% end %>
<div class="progress_arrow purple z-depth-3">
    <div class="container">
        <a class="left white-text" id="prev_progress">
            <i class="material-icons left">chevron_left</i>
            previous
    </a>
        <a class="right white-text" id="next_progress">
            next
      <i class="material-icons right">chevron_right</i>
        </a>
    </div>
</div>

app/views/orders/show.html.erb
<span><%= @order.id %></span><br>
<span><%= @order.transaction_id %></span><br>
<span><%= @order.cart_id %></span><br>
<span><%= @order.phone %></span><br>
<span><%= @order.email %></span><br>
<span><%= @order.ip_address %></span><br>
<p>Shipping</p>
<span><%= @order.shipping.name %></span><br>
<span><%= @order.shipping.street_address %></span><br>
<span><%= @order.shipping.extended_address %></span><br>
<span><%= @order.shipping.city %> <%= @order.shipping.state %> <%= @order.shipping.postal_code %></span><br>
<span><%= @order.shipping.country %></span><br>
<p>Billing</p>
<span><%= @order.billing.name %></span><br>
<span><%= @order.billing.street_address %></span><br>
<span><%= @order.billing.extended_address %></span><br>
<span><%= @order.billing.city %> <%= @order.billing.state %> <%= @order.billing.postal_code %></span><br>
<span><%= @order.billing.country %></span><br>
<span><%= link_to 'Back', orders_path %></span><br>