config/routes.rb
Rails.application.routes.draw do
    #standard route
    root      'pages#home'
    match     'contact' => 'contacts#new', via: [:get, :post]
    resources :products
    resources :cart_items, only: [:create, :update, :destroy], constraints: {format: 'js'}
    match     'cart' => 'carts#show', via: :get
    resources :carts, only: [:index, :destroy]
    match     'checkout' => 'orders#new', via: :get
    resources :orders, except: [:new]

    #devise
    devise_for :admins, skip: [:registrations, :unlock]
    devise_scope :admin do
        post "/admins/unlock" => "devise/unlocks#create", as: :admin_unlock
        get "/admins/unlock" => "devise/unlocks#show", as: ''
    end

    #console
    get 'console', to: 'console#core'
    #admin manager
    resources :admins, except: [:index, :show]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :recoverable, :rememberable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :trackable, :validatable, :lockable
end

app/models/background.rb
class Background < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
  validates :page,
    presence: true

  enum page: [:home, :about]
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  include Address
  belongs_to :order
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :visitor
  has_many :cart_items, :dependent => :destroy
  has_one :order

  validates :visitor,
    presence: true

  def add_product(product_id)
    if Product.find(product_id) && !( cart_item = included?(product_id))
      return cart_items.create(product_id: product_id)
    else
      return cart_item
    end
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def included?(product_id)
    cart_items.find_by(product_id: product_id)
  end

  def total
    cart_items.to_a.sum { |item| item.sum }
  end

  def purchase
    self.purchased = true
    cart_items.to_a.each { |item| item.purchase }
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  validates :product,
            presence: true
  validates :cart,
            presence: true
  validates :quantity,
            numericality: {greater_than: 0, less_than_or_equal_to: :stock_quantity, only_integer: true}

  def sum
    product.price * quantity
  end

  def purchase
    product.purchase(quantity)
  end

  private
  def stock_quantity
    product.stock
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name, validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :subject,  validate: ["Enquiry", "Feedback", "Support"]
  attributes :message, validate: true
  attributes :nickname,  captcha: true

  append :remote_ip, :user_agent

  def headers
    {
      subject: "Site Contact - #{subject}",
      to: "gristlegrime.dev@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
  validates :name,
    presence: true
  validates :description,
    presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_one :shipping, inverse_of: :order, dependent: :destroy
  has_one :billing, inverse_of: :order, dependent: :destroy

  accepts_nested_attributes_for :shipping, reject_if: :all_blank
  accepts_nested_attributes_for :billing, reject_if: :all_blank

  validate :suffice_stock?
  validates :cart,
    presence: true
  validates :phone,
    presence: true,
    length: { maximum: 30 }
  validates :email,
    presence: true,
    length: { maximum: 50 },
    format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
  validates :ip_address,
    presence: true,
    format: { with: Resolv::AddressRegex }
  validates :transaction_id,
    length: { maximum: 10 }

  before_save :clean_up
  after_save :mark_as_purchased

  def purchase_with(payment_nonce)
    @result = Braintree::Transaction.sale(
      amount: cart.total,
      payment_method_nonce: payment_nonce,
      customer: {
        first_name: billing.name,
        phone: phone,
        email: email
      },
      billing: {
        first_name: billing.name,
        street_address: billing.street_address,
        extended_address: billing.extended_address,
        locality: billing.city,
        region: billing.state,
        postal_code: billing.postal_code,
        country_name: billing.country
      },
      shipping: {
        first_name: shipping.name,
        street_address: shipping.street_address,
        extended_address: shipping.extended_address,
        locality: shipping.city,
        region: shipping.state,
        postal_code: shipping.postal_code,
        country_name: shipping.country
      },
      options: {
        submit_for_settlement: true
      }
    )

    puts_result
  end

  private
  def suffice_stock?

  end

  def clean_up
    self.email = email.strip.downcase
  end

  def puts_result
    if @result.success?
      puts "success!: #{@result.transaction.id}"
      self.transaction_id = @result.transaction.id
      return true
    elsif @result.transaction
      puts "Error processing transaction:"
      puts "  code: #{@result.transaction.processor_@result_code}"
      puts "  text: #{@result.transaction.processor_@result_text}"
    else
      @result.errors.each do |error|
        puts error.message
        return false
      end
    end
  end

  def mark_as_purchased
    cart.purchase
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photos, inverse_of: :product, dependent: :destroy
  has_many :materials, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank

  default_scope -> { order(created_at: :desc) }

  monetize :price_cents

  validates :price,
    presence: true,
    numericality: { greater_than: 0 }
  validates :photos,
    presence: true
  validates :length, :width, :height,
    presence: true,
    numericality: { greater_than_or_equal_to: 1, only_integer: true }
  validates :limited_to,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :stock,
    presence: true,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def limited?
    limited_to > 0
  end

  def humanized_dimensions(l='L', w='W', h='H')
    return "#{l}: #{length}cm <strong>x</strong> #{w}: #{width}cm <strong>x</strong> #{h}: #{height}cm".html_safe
  end

  def purchase(quantity)
    self.stock -= quantity
  end
end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
  include Address
  belongs_to :order
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_many :carts

  validates :visit_count,
    numericality: { greater_than_or_equal_to: 1, only_integer: true }

  before_create :init

  def visiting
    if last_visit_at < 2.hours.ago
      self.current_visit_at = self.last_visit_at = Time.now
      self.visit_count += 1
    else
      current_visit_at = Time.now
    end
  end

  private
  def init
    self.current_visit_at = self.last_visit_at = Time.now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :get_cart

  def index
    @carts = Cart.all
  end

  def show
  end

  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
    before_action :masked_authenticate!

    def core
        @admins = Admin.all
        @products = Product.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/console/_admins_module.html.erb
<%= link_to new_admin_path, class: "btn" do %>
    <i class="material-icons left">person_add</i>
    Register new admin
<% end %>
<div class="list">
    <table class="highlight">
        <thead>
            <tr>
                <th>Admin id</th>
                <th>Email</th>
                <th>Recent sign in at</th>
                <th>Recent sign in ip</th>
                <th>Failed sign in attempt</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
                <tr>
                    <td><%= admin.id %></td>
                    <td><%= admin.email %></td>
                    <td><%= admin.current_sign_in_at.in_time_zone("Kuala Lumpur").to_formatted_s(:short) %></td>
                    <td><%= admin.current_sign_in_ip %></td>
                    <td><%= admin.failed_attempts %></td>
                    <td>
                        <%= link_to "edit", edit_admin_path(admin) %>
                    </td>
                    <td>
                        <% unless admin == current_admin %>
                            <%= link_to "delete", admin_path(admin), method: :delete, data: {confirm: "Delete #{admin.email}?"} %>
                        <% else %>
                            Self
                                <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/console/_products_module.html.erb
<%= link_to new_product_path, class: "btn" do %>
    <i class="material-icons left">person_add</i>
    Register new product
<% end %>
<div class="list">
    <table class="highlight">
        <thead>
            <tr>
                <th>Product id</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
                <tr>
                    <td><%= product.id %></td>
                    <td>
                        <%= link_to "edit", edit_product_path(product) %>
                    </td>
                    <td>
                        <%= link_to "delete", product_path(product), method: :delete, data: {confirm: "Delete #{product.id}?"} %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/console/_tabs.html.erb
<div class="row">
    <ul class="tabs">
        <li class="tab col s3"><a href="#admins">Admins</a></li>
        <li class="tab col s3"><a href="#products">Products</a></li>
    </ul>
    <div id="admins" class="col s10 offset-s1">
        <div class="seperator"></div>
        <%= render 'admins_module' %>
    </div>
    <div id="products" class="col s10 offset-s1">
        <div class="seperator"></div>
        <%= render 'products_module' %>
    </div>
</div>

app/views/console/core.html.erb
<% provide(:title, "Mashirona - Admin console") %>
<% flash.each do |message_type, message| %>
    <div class="chip <%= message_type %>">
        <%= message %>
        <i class="material-icons">close</i>
    </div>
<% end %>
<div class="seperator"></div>
<div>
    <% if admin_signed_in? %>
        <h5>
            Signed in as <%= current_admin.email %> | <%= link_to "Sign out", destroy_admin_session_path, :method => :delete %>
        </h5>
        <%= render 'tabs' %>
    <% else %>
        <h5>
            Not signed in | <%= link_to "Sign in", new_admin_session_path %>
        </h5>
    <% end %>
</div>
<script type="text/javascript">
    $("main").css("padding", 0);
</script>