config/routes.rb
Rails.application.routes.draw do
    #standard route
    root      'pages#home'
    match     'contact' => 'contacts#new', via: [:get, :post]
    resources :products
    resources :cart_items, only: [:create, :update, :destroy], constraints: {format: 'js'}
    match     'cart' => 'carts#show', via: :get
    resources :carts, only: [:index, :destroy]
    match     'checkout' => 'orders#new', via: :get
    resources :orders, except: [:new]

    #devise
    devise_for :admins, skip: [:registrations, :unlock]
    devise_scope :admin do
        post "/admins/unlock" => "devise/unlocks#create", as: :admin_unlock
        get "/admins/unlock" => "devise/unlocks#show", as: ''
    end

    #console
    get 'console', to: 'console#core'
    #admin manager
    resources :admins, except: [:index, :show]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :recoverable, :rememberable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :trackable, :validatable, :lockable
end

app/models/background.rb
class Background < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
  validates :page,
    presence: true

  enum page: [:home, :about]
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  include Address
  belongs_to :order
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :visitor
  has_many :cart_items, :dependent => :destroy
  has_one :order

  validates :visitor,
    presence: true

  def add_product(product_id)
    if Product.find(product_id) && !( cart_item = included?(product_id))
      return cart_items.create(product_id: product_id)
    else
      return cart_item
    end
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def included?(product_id)
    cart_items.find_by(product_id: product_id)
  end

  def total
    cart_items.to_a.sum { |item| item.sum }
  end

  def purchase
    self.purchased = true
    cart_items.to_a.each { |item| item.purchase }
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  validates :product,
            presence: true
  validates :cart,
            presence: true
  validates :quantity,
            numericality: {greater_than: 0, less_than_or_equal_to: :stock_quantity, only_integer: true}

  def sum
    product.price * quantity
  end

  def purchase
    product.purchase(quantity)
  end

  private
  def stock_quantity
    product.stock
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name, validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :subject,  validate: ["Enquiry", "Feedback", "Support"]
  attributes :message, validate: true
  attributes :nickname,  captcha: true

  append :remote_ip, :user_agent

  def headers
    {
      subject: "Site Contact - #{subject}",
      to: "gristlegrime.dev@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
  validates :name,
    presence: true
  validates :description,
    presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_one :shipping, inverse_of: :order, dependent: :destroy
  has_one :billing, inverse_of: :order, dependent: :destroy

  accepts_nested_attributes_for :shipping, reject_if: :all_blank
  accepts_nested_attributes_for :billing, reject_if: :all_blank

  validate :suffice_stock?
  validates :cart,
    presence: true
  validates :phone,
    presence: true,
    length: { maximum: 30 }
  validates :email,
    presence: true,
    length: { maximum: 50 },
    format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
  validates :ip_address,
    presence: true,
    format: { with: Resolv::AddressRegex }
  validates :transaction_id,
    length: { maximum: 10 }

  before_save :clean_up
  after_save :mark_as_purchased

  def purchase_with(payment_nonce)
    @result = Braintree::Transaction.sale(
      amount: cart.total,
      payment_method_nonce: payment_nonce,
      customer: {
        first_name: billing.name,
        phone: phone,
        email: email
      },
      billing: {
        first_name: billing.name,
        street_address: billing.street_address,
        extended_address: billing.extended_address,
        locality: billing.city,
        region: billing.state,
        postal_code: billing.postal_code,
        country_name: billing.country
      },
      shipping: {
        first_name: shipping.name,
        street_address: shipping.street_address,
        extended_address: shipping.extended_address,
        locality: shipping.city,
        region: shipping.state,
        postal_code: shipping.postal_code,
        country_name: shipping.country
      },
      options: {
        submit_for_settlement: true
      }
    )

    puts_result
  end

  private
  def suffice_stock?

  end

  def clean_up
    self.email = email.strip.downcase
  end

  def puts_result
    if @result.success?
      puts "success!: #{@result.transaction.id}"
      self.transaction_id = @result.transaction.id
      return true
    elsif @result.transaction
      puts "Error processing transaction:"
      puts "  code: #{@result.transaction.processor_@result_code}"
      puts "  text: #{@result.transaction.processor_@result_text}"
    else
      @result.errors.each do |error|
        puts error.message
        return false
      end
    end
  end

  def mark_as_purchased
    cart.purchase
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader

  validates :image,
    presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photos, inverse_of: :product, dependent: :destroy
  has_many :materials, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank

  default_scope -> { order(created_at: :desc) }

  monetize :price_cents

  validates :price,
    presence: true,
    numericality: { greater_than: 0 }
  validates :photos,
    presence: true
  validates :length, :width, :height,
    presence: true,
    numericality: { greater_than_or_equal_to: 1, only_integer: true }
  validates :limited_to,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :stock,
    presence: true,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def limited?
    limited_to > 0
  end

  def humanized_dimensions(l='L', w='W', h='H')
    return "#{l}: #{length}cm <strong>x</strong> #{w}: #{width}cm <strong>x</strong> #{h}: #{height}cm".html_safe
  end

  def purchase(quantity)
    self.stock -= quantity
  end
end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
  include Address
  belongs_to :order
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_many :carts

  validates :visit_count,
    numericality: { greater_than_or_equal_to: 1, only_integer: true }

  before_create :init

  def visiting
    if last_visit_at < 2.hours.ago
      self.current_visit_at = self.last_visit_at = Time.now
      self.visit_count += 1
    else
      current_visit_at = Time.now
    end
  end

  private
  def init
    self.current_visit_at = self.last_visit_at = Time.now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :get_cart

  def index
    @carts = Cart.all
  end

  def show
  end

  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/_form.html.erb
<div class="row">
    <div class="col s6 offset-s3 l4 offset-l4">
        <%= simple_form_for(@admin) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :email %>
                <%= f.input :password %>
                <%= f.input :password_confirmation %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, class: 'btn col s12' %>
            </div>
        <% end %>
        <div class="seperator"></div>
        <%= link_to "Back", :back, class: 'red btn col s12', data: {confirm: "Unsaved changes will be removed. Are you sure?"} %>
    </div>
</div>

app/views/admins/edit.html.erb
<h3 class="center">Editing Admin</h3>
<div style="height: 2vw;"></div>
<%= render 'form' %>

app/views/admins/new.html.erb
<h3 class="center">New Admin</h3>
<div style="height: 2vw;"></div>
<%= render 'form' %>

app/views/layouts/_ext_resources.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.3.0/animate.min.css" rel="stylesheet">
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.js"></script>

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#000000">
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_navigation.html.erb
<div class="side-navigation hide-on-med-and-down">
    <%= image_tag("mashirona_brand_logo_negative.svg", class: "side-nav_background_logo") %>
    <ul class="side-nav fixed">
        <%= render 'layouts/navigation_links' %>
        <%= image_tag("mashirona_brand_logo.svg", class: "side-nav_logo") %>
    </ul>
    <div class="side-nav-background"></div>
</div>
<div class="navbar-fixed hide-on-large-only">
    <nav>
        <div class="nav-wrapper">
            <ul>
                <%= render 'layouts/navigation_links' %>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Home', root_path %></li>
<li class="hide-on-med-and-down"><%= link_to 'About', root_path + '#about' %></li>
<li><%= link_to 'Contact', contact_path %></li>
<li><%= link_to 'Store', products_path %></li>
<li><%= link_to 'Cart', checkout_path %></li>

app/views/layouts/_seo.html.erb
<% desc = "get a god damn copywriter!!!" %>
<% keyw = "..." %>

<meta name="description" content="<%= desc %>">
<meta name="keyword" content="<%= keyw %>">
<meta property="og:title" content="<%= content_for?(:og_title) ? yield(:og_title) : "Mashirona" %>">
<meta property="og:type" content="website">
<meta property="og:description" content="<%= content_for?(:og_desc) ? yield(:og_desc) : desc %>">
<meta property="og:image" content="<%= content_for?(:og_image) ? yield(:og_image) : "/og-200x200.png" %>">

app/views/layouts/_title.html.erb
<div class="center-align section title">
    <%= image_tag("mashirona_font_logo.svg", class: "title_logo") %>
    <h5 class="thin">some catchline</h5>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= content_for?(:title) ? yield(:title) : "Mashirona" %></title>
        <%= render 'layouts/seo' %>
        <meta content="True" name="HandheldFriendly">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="viewport" content="width=device-width">
        <%= render 'layouts/favicon' %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/ext_resources' %>
    </head>
    <body>
        <%= include_gon() %>
        <%= render 'layouts/navigation' unless admin_signed_in? %>
        <main>
            <%= render 'layouts/title' unless action_name == 'home' %>
            <%= yield %>
        </main>
    </body>
</html>

app/views/pages/home.html.erb
<% if @home && @abouts %>
    <div class="home" style="background-image: url('<%= @home.image.url %>')">
        <div class="center-align">
            <%= image_tag("mashirona_font_logo.svg", class: "home_logo") %>
            <h4>Lorem Ipsum</h4>
        </div>
    </div>
    <div id='about'>
        <% @abouts.each do |about| %>
            <div class="about">
                <%= image_tag(about.image.url) %>
            </div>
        <% end %>
    </div>
<% end %>